### PR TITLE
fix: accept return fd should be marked as socket

### PR DESCRIPTION
**Pull request by shuai132**

### CODE REVIEW

**Review by idealvin — APPROVED** [review]
Good job!

**Comment by idealvin** [comment]
@shuai132
Merged. Thanks for your contribution!

**Comment by idealvin** [comment]
It is better to mark the fd as socket at the end. See another fix [here](https://github.com/idealvin/cocoyaxi/commit/7954b7cb8d64ba43d3ed2eb0fec28de05a7dd813).

**Comment by shuai132** [comment]
Thanks,
I don't know which is better at first, because when `accept` called from pure thread(not from coroutine -- co::gSched is null) and `read/write` from coroutine, `read/write` should block or not?
if mark the fd as socket at the end, it will still works well(no block).
emmm... i think it's better now!!!

**Comment by idealvin** [comment]
> Thanks, I don't know which is better at first, because when `accept` called from pure thread(not from coroutine -- co::gSched is null) and `read/write` from coroutine, `read/write` should block or not? if mark the fd as socket at the end, it will still works well(no block). emmm... i think it's better now!!!

Yes. It should work on any case.

**Pull request merged**
